site_name: hypergrad
site_description: Simple and extensible hypergradient for PyTorch
site_author: Ryuichiro Hataya
site_url: https://mosko.tokyo/hypergrad
repo_name: moskomule/hypergrad
repo_url: https://github.com/moskomule/hypergrad
edit_uri: blob/main/docs

theme:
  name: material

markdown_extensions:
   # mathjax
  - pymdownx.arithmatex:
      generic: true

  # syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

