name: pytest

on: [ "push" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          pip install hatch
          hatch env create tests

      - name: test
        run: |
          hatch run tests:pytest
